//go:build ignore

/*
Copyright The k3sm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// gen_tlds regenerates tlds_iana.go, the vendored IANA root-zone TLD snapshot
// behind IsReservedSuffix. Run it through go generate from pkg/dns:
//
//	go generate ./pkg/dns
//
// It fetches the pinned canonical list (never a search result), validates every
// entry as a lower-case DNS label, and writes a sorted Go table stamped with the
// list's own version line, so a regeneration diff shows exactly what IANA changed.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

// tldListURL is the pinned canonical source of record.
const tldListURL = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt"

const outFile = "tlds_iana.go"

func main() {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(tldListURL)
	if err != nil {
		log.Fatalf("fetch %s: %v", tldListURL, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("fetch %s: status %s", tldListURL, resp.Status)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("read %s: %v", tldListURL, err)
	}

	var version string
	var tlds []string
	sc := bufio.NewScanner(bytes.NewReader(body))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		switch {
		case line == "":
			continue
		case strings.HasPrefix(line, "#"):
			if version == "" {
				version = strings.TrimSpace(strings.TrimPrefix(line, "#"))
			}
			continue
		}
		label := strings.ToLower(line)
		if !validLabel(label) {
			log.Fatalf("IANA list entry %q is not a DNS label", line)
		}
		tlds = append(tlds, label)
	}
	if err := sc.Err(); err != nil {
		log.Fatalf("scan %s: %v", tldListURL, err)
	}
	if version == "" || len(tlds) < 1000 {
		log.Fatalf("IANA list looks truncated: version %q, %d entries", version, len(tlds))
	}
	sort.Strings(tlds)

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by gen_tlds.go; DO NOT EDIT.")
	fmt.Fprintln(&b)
	header, err := os.ReadFile("../../hack/boilerplate/boilerplate.go.txt")
	if err != nil {
		log.Fatalf("read license header: %v", err)
	}
	b.Write(bytes.TrimRight(header, "\n"))
	fmt.Fprintln(&b)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package dns")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "// ianaTLDs is the IANA root-zone TLD snapshot from %s.\n", tldListURL)
	fmt.Fprintf(&b, "// Snapshot: %s.\n", version)
	fmt.Fprintln(&b, "// Regenerate with go generate ./pkg/dns (gen_tlds.go).")
	fmt.Fprintln(&b, "var ianaTLDs = map[string]struct{}{")
	for _, t := range tlds {
		fmt.Fprintf(&b, "\t%q: {},\n", t)
	}
	fmt.Fprintln(&b, "}")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("gofmt generated source: %v", err)
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", outFile, err)
	}
	fmt.Printf("wrote %s: %d TLDs (%s)\n", outFile, len(tlds), version)
}

// validLabel mirrors the package's isDNSLabel (a generator cannot import the
// package it generates into).
func validLabel(s string) bool {
	if len(s) == 0 || len(s) > 63 {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= 'a' && c <= 'z', c >= '0' && c <= '9':
		case c == '-':
			if i == 0 || i == len(s)-1 {
				return false
			}
		default:
			return false
		}
	}
	return true
}
